//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.CommandLine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NuGetResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NuGetResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.CommandLine.NuGetResources", typeof(NuGetResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file &apos;{0}&apos; to package as &apos;{1}&apos;.
        /// </summary>
        public static string AddFileToPackage {
            get {
                return ResourceManager.GetString("AddFileToPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous command &apos;{0}&apos;. Possible values: {1}..
        /// </summary>
        public static string AmbiguousCommand {
            get {
                return ResourceManager.GetString("AmbiguousCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous option &apos;{0}&apos;. Possible values: {1}..
        /// </summary>
        public static string AmbiguousOption {
            get {
                return ResourceManager.GetString("AmbiguousOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or an empty string..
        /// </summary>
        public static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty..
        /// </summary>
        public static string ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building project &apos;{0}&apos; for target framework &apos;{1}&apos;..
        /// </summary>
        public static string BuildingProjectTargetingFramework {
            get {
                return ResourceManager.GetString("BuildingProjectTargetingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; not found..
        /// </summary>
        public static string ConfigCommandKeyNotFound {
            get {
                return ResourceManager.GetString("ConfigCommandKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (y/N) .
        /// </summary>
        public static string ConsoleConfirmMessage {
            get {
                return ResourceManager.GetString("ConsoleConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        public static string ConsoleConfirmMessageAccept {
            get {
                return ResourceManager.GetString("ConsoleConfirmMessageAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description was provided for this command..
        /// </summary>
        public static string DefaultCommandDescription {
            get {
                return ResourceManager.GetString("DefaultCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the symbol server.
        /// </summary>
        public static string DefaultSymbolServer {
            get {
                return ResourceManager.GetString("DefaultSymbolServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已取消删除.
        /// </summary>
        public static string DeleteCommandCanceled_chs {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已取消刪除.
        /// </summary>
        public static string DeleteCommandCanceled_cht {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstranit zrušené.
        /// </summary>
        public static string DeleteCommandCanceled_csy {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Löschvorgang wurde abgebrochen..
        /// </summary>
        public static string DeleteCommandCanceled_deu {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación cancelada.
        /// </summary>
        public static string DeleteCommandCanceled_esp {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression annulée.
        /// </summary>
        public static string DeleteCommandCanceled_fra {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancellazione teminata.
        /// </summary>
        public static string DeleteCommandCanceled_ita {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除は取り消されました.
        /// </summary>
        public static string DeleteCommandCanceled_jpn {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제가 취소됨.
        /// </summary>
        public static string DeleteCommandCanceled_kor {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie anulowane.
        /// </summary>
        public static string DeleteCommandCanceled_plk {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir cancelado.
        /// </summary>
        public static string DeleteCommandCanceled_ptb {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление отменено.
        /// </summary>
        public static string DeleteCommandCanceled_rus {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme iptal edildi.
        /// </summary>
        public static string DeleteCommandCanceled_trk {
            get {
                return ResourceManager.GetString("DeleteCommandCanceled_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将从 {2} 中删除 {0} {1}。是否要继续?.
        /// </summary>
        public static string DeleteCommandConfirm_chs {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} 會從 {2} 刪除。您要繼續嗎?.
        /// </summary>
        public static string DeleteCommandConfirm_cht {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} bude odstraněno z {2}. Chcete pokračovat?.
        /// </summary>
        public static string DeleteCommandConfirm_csy {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} wird aus &quot;{2}&quot; gelöscht. Möchten Sie den Vorgang fortsetzen?.
        /// </summary>
        public static string DeleteCommandConfirm_deu {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} se eliminará de {2}. ¿Desea continuar?.
        /// </summary>
        public static string DeleteCommandConfirm_esp {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} sera supprimé de {2}. Souhaitez-vous continuer ?.
        /// </summary>
        public static string DeleteCommandConfirm_fra {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} sarà cancellato da {2}. Vuoi continuare?.
        /// </summary>
        public static string DeleteCommandConfirm_ita {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} は {2} から削除されます。続行しますか?.
        /// </summary>
        public static string DeleteCommandConfirm_jpn {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}이(가) {2}에서 삭제됩니다. 계속하시겠습니까?.
        /// </summary>
        public static string DeleteCommandConfirm_kor {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element {0} {1} zostanie usunięty z {2}. Czy chcesz kontynuować?.
        /// </summary>
        public static string DeleteCommandConfirm_plk {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} será excluído do {2}. Deseja continuar?.
        /// </summary>
        public static string DeleteCommandConfirm_ptb {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будет выполнено удаление {0} {1} из {2}. Продолжить?.
        /// </summary>
        public static string DeleteCommandConfirm_rus {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} öğeleri {2} konumundan silinecek. Devam etmek istiyor musunuz?.
        /// </summary>
        public static string DeleteCommandConfirm_trk {
            get {
                return ResourceManager.GetString("DeleteCommandConfirm_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已成功删除 {0} {1}。.
        /// </summary>
        public static string DeleteCommandDeletedPackage_chs {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} 已成功刪除。.
        /// </summary>
        public static string DeleteCommandDeletedPackage_cht {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} bylo úspěšně odstraněno..
        /// </summary>
        public static string DeleteCommandDeletedPackage_csy {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} wurde erfolgreich gelöscht..
        /// </summary>
        public static string DeleteCommandDeletedPackage_deu {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} se ha eliminado correctamente..
        /// </summary>
        public static string DeleteCommandDeletedPackage_esp {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} a été correctement supprimé..
        /// </summary>
        public static string DeleteCommandDeletedPackage_fra {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} è stato correttamente cancellato..
        /// </summary>
        public static string DeleteCommandDeletedPackage_ita {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} は正常に削除されました。.
        /// </summary>
        public static string DeleteCommandDeletedPackage_jpn {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}이(가) 삭제되었습니다..
        /// </summary>
        public static string DeleteCommandDeletedPackage_kor {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie usunięto element {0} {1}..
        /// </summary>
        public static string DeleteCommandDeletedPackage_plk {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} foi excluído com sucesso..
        /// </summary>
        public static string DeleteCommandDeletedPackage_ptb {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление {0} {1} выполнено..
        /// </summary>
        public static string DeleteCommandDeletedPackage_rus {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} başarıyla silindi..
        /// </summary>
        public static string DeleteCommandDeletedPackage_trk {
            get {
                return ResourceManager.GetString("DeleteCommandDeletedPackage_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在从 {2} 中删除 {0} {1}。.
        /// </summary>
        public static string DeleteCommandDeletingPackage_chs {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在從 {2} 刪除 {0} {1}。.
        /// </summary>
        public static string DeleteCommandDeletingPackage_cht {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá odstraňování {0} {1} z {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_csy {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} wird aus &quot;{2}&quot; gelöscht..
        /// </summary>
        public static string DeleteCommandDeletingPackage_deu {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando {0} {1} de {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_esp {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de {0} {1} de {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_fra {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellando {0} {1} da {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_ita {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} から {0} {1} を削除しています。.
        /// </summary>
        public static string DeleteCommandDeletingPackage_jpn {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}을(를) {2}에서 삭제하고 있습니다..
        /// </summary>
        public static string DeleteCommandDeletingPackage_kor {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie elementu {0} {1} z {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_plk {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluindo {0} {1} do {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_ptb {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление {0} {1} из {2}..
        /// </summary>
        public static string DeleteCommandDeletingPackage_rus {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} öğeleri {2} konumundan siliniyor..
        /// </summary>
        public static string DeleteCommandDeletingPackage_trk {
            get {
                return ResourceManager.GetString("DeleteCommandDeletingPackage_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet.exe file on path {0} needs to be unblocked after downloading..
        /// </summary>
        public static string Error_NuGetExeNeedsToBeUnblockedAfterDownloading {
            get {
                return ResourceManager.GetString("Error_NuGetExeNeedsToBeUnblockedAfterDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `project.json` pack is disabled in the current NuGet version, and will be permanently removed in a future version.
        ///Please consider migrating &apos;{0}&apos; to `PackageReference` and using the pack targets.
        ///You can set the &apos;{1}&apos; environment variable to &apos;true&apos; to temporarily reenable this functionality..
        /// </summary>
        public static string Error_ProjectJson_Deprecated_And_Removed {
            get {
                return ResourceManager.GetString("Error_ProjectJson_Deprecated_And_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceProvider 属性为 null。.
        /// </summary>
        public static string Error_SourceProviderIsNull_chs {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 屬性 SourceProvider 為 Null。.
        /// </summary>
        public static string Error_SourceProviderIsNull_cht {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vlastnost SourceProvider má hodnotu null..
        /// </summary>
        public static string Error_SourceProviderIsNull_csy {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Eigenschaft &quot;SourceProvider&quot; ist null..
        /// </summary>
        public static string Error_SourceProviderIsNull_deu {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La propiedad SourceProvider es nula..
        /// </summary>
        public static string Error_SourceProviderIsNull_esp {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le @@@fournisseur de source de propriété est nul..
        /// </summary>
        public static string Error_SourceProviderIsNull_fra {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property sSourceProvider è nullo..
        /// </summary>
        public static string Error_SourceProviderIsNull_ita {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロパティ SourceProvider は null です。.
        /// </summary>
        public static string Error_SourceProviderIsNull_jpn {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceProvider 속성이 null입니다..
        /// </summary>
        public static string Error_SourceProviderIsNull_kor {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwość SourceProvider ma wartość null..
        /// </summary>
        public static string Error_SourceProviderIsNull_plk {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O item SourceProvider de propriedade é nulo..
        /// </summary>
        public static string Error_SourceProviderIsNull_ptb {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceProvider свойства имеет значение NULL..
        /// </summary>
        public static string Error_SourceProviderIsNull_rus {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellik SourceProvider null..
        /// </summary>
        public static string Error_SourceProviderIsNull_trk {
            get {
                return ResourceManager.GetString("Error_SourceProviderIsNull_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build &apos;{0}&apos;..
        /// </summary>
        public static string FailedToBuildProject {
            get {
                return ResourceManager.GetString("FailedToBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}, if this extension was downloaded from the internet please make sure it got unblocked (right click, properties, unblock)..
        /// </summary>
        public static string FailedToLoadExtension {
            get {
                return ResourceManager.GetString("FailedToLoadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load {0}{1}.
        /// </summary>
        public static string FailedToLoadExtensionDuringMefComposition {
            get {
                return ResourceManager.GetString("FailedToLoadExtensionDuringMefComposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Y] Yes  [A] Yes to All  [N] No  [L] No to All ?.
        /// </summary>
        public static string FileConflictChoiceText {
            get {
                return ResourceManager.GetString("FileConflictChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is not added because the package already contains file &apos;{1}&apos;.
        /// </summary>
        public static string FileNotAddedToPackage {
            get {
                return ResourceManager.GetString("FileNotAddedToPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 project with a packages.config file. ({0}).
        /// </summary>
        public static string FoundProject {
            get {
                return ResourceManager.GetString("FoundProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} projects with a packages.config file. ({1}).
        /// </summary>
        public static string FoundProjects {
            get {
                return ResourceManager.GetString("FoundProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information, visit {0}.
        /// </summary>
        public static string HelpCommandForMoreInfo {
            get {
                return ResourceManager.GetString("HelpCommandForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; contains invalid package references. .
        /// </summary>
        public static string InstallCommandInvalidPackageReference {
            get {
                return ResourceManager.GetString("InstallCommandInvalidPackageReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All packages listed in {0} are already installed..
        /// </summary>
        public static string InstallCommandNothingToInstall {
            get {
                return ResourceManager.GetString("InstallCommandNothingToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package &quot;{0}&quot; is already installed..
        /// </summary>
        public static string InstallCommandPackageAlreadyExists {
            get {
                return ResourceManager.GetString("InstallCommandPackageAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version string specified for package reference &apos;{0}&apos; is invalid..
        /// </summary>
        public static string InstallCommandPackageReferenceInvalidVersion {
            get {
                return ResourceManager.GetString("InstallCommandPackageReferenceInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package restore is disabled. To enable it, open the Visual Studio Options dialog, click on Package Manager node and check &apos;{0}&apos;. You can also enable package restore by setting the environment variable &apos;EnableNuGetPackageRestore&apos; to &apos;true&apos;..
        /// </summary>
        public static string InstallCommandPackageRestoreConsentNotFound {
            get {
                return ResourceManager.GetString("InstallCommandPackageRestoreConsentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find package &apos;{0}&apos;.
        /// </summary>
        public static string InstallCommandUnableToFindPackage {
            get {
                return ResourceManager.GetString("InstallCommandUnableToFindPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing package &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        public static string InstallPackageMessage {
            get {
                return ResourceManager.GetString("InstallPackageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: invalid arguments..
        /// </summary>
        public static string InvalidArguments {
            get {
                return ResourceManager.GetString("InvalidArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid AssemblyInformationalVersion &apos;{0}&apos; on assembly &apos;{1}&apos;; falling back to AssemblyVersion &apos;{2}&apos;..
        /// </summary>
        public static string InvalidAssemblyInformationalVersion {
            get {
                return ResourceManager.GetString("InvalidAssemblyInformationalVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages.config, project or solution file specified. Use the -self switch to update NuGet.exe..
        /// </summary>
        public static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid option value: &apos;{0} {1}&apos;.
        /// </summary>
        public static string InvalidOptionValueError {
            get {
                return ResourceManager.GetString("InvalidOptionValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified source &apos;{0}&apos; is invalid. Please provide a valid source..
        /// </summary>
        public static string InvalidSource {
            get {
                return ResourceManager.GetString("InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No packages found..
        /// </summary>
        public static string ListCommandNoPackages {
            get {
                return ResourceManager.GetString("ListCommandNoPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the NuGet gallery.
        /// </summary>
        public static string LiveFeed {
            get {
                return ResourceManager.GetString("LiveFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for installed packages in &apos;{0}&apos;..
        /// </summary>
        public static string LookingForInstalledPackages {
            get {
                return ResourceManager.GetString("LookingForInstalledPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing option value for: &apos;{0}&apos;.
        /// </summary>
        public static string MissingOptionValueError {
            get {
                return ResourceManager.GetString("MissingOptionValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuild auto-detection: using msbuild version &apos;{0}&apos; from &apos;{1}&apos;..
        /// </summary>
        public static string MSBuildAutoDetection {
            get {
                return ResourceManager.GetString("MSBuildAutoDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsBuild.exe does not exist at &apos;{0}&apos;..
        /// </summary>
        public static string MsBuildDoesNotExistAtPath {
            get {
                return ResourceManager.GetString("MsBuildDoesNotExistAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Msbuild from &apos;{0}&apos;..
        /// </summary>
        public static string MSbuildFromPath {
            get {
                return ResourceManager.GetString("MSbuildFromPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load msbuild Toolset.
        /// </summary>
        public static string MsbuildLoadToolSetError {
            get {
                return ResourceManager.GetString("MsbuildLoadToolSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBuildPath : {0}  doesn&apos;t not exist..
        /// </summary>
        public static string MsbuildPathNotExist {
            get {
                return ResourceManager.GetString("MsbuildPathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found multiple project files for &apos;{0}&apos;..
        /// </summary>
        public static string MultipleProjectFilesFound {
            get {
                return ResourceManager.GetString("MultipleProjectFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未提供 API 密钥并且找不到 {0} 的 API 密钥。若要保存源的 API 密钥，请使用 &quot;setApiKey&quot; 命令。.
        /// </summary>
        public static string NoApiKeyFound_chs {
            get {
                return ResourceManager.GetString("NoApiKeyFound_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未提供 API 索引鍵，也找不到 {0} 的 API 索引鍵。如要儲存來源的 API 索引鍵，請使用 &apos;setApiKey&apos; 命令。.
        /// </summary>
        public static string NoApiKeyFound_cht {
            get {
                return ResourceManager.GetString("NoApiKeyFound_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebyl zadán žádný klíč API a nebyl nalezen žádný klíč API Key pro {0}. Chcete-li uložit klíč API pro určitý zdroj, použijte příkaz setApiKey..
        /// </summary>
        public static string NoApiKeyFound_csy {
            get {
                return ResourceManager.GetString("NoApiKeyFound_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein API-Schlüssel bereitgestellt bzw. für &quot;{0}&quot; gefunden. Verwenden Sie zum Speichern eines API-Schlüssels für eine Quelle den Befehl &quot;setApiKey&quot;..
        /// </summary>
        public static string NoApiKeyFound_deu {
            get {
                return ResourceManager.GetString("NoApiKeyFound_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha proporcionado ninguna clave API ni tampoco se ha podido encontrar una para {0}. Para guardar una clave API para un origen use el comando &apos;setApiKey&apos;..
        /// </summary>
        public static string NoApiKeyFound_esp {
            get {
                return ResourceManager.GetString("NoApiKeyFound_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune clé API n&apos;a été fournie et aucune clé API n&apos;a été trouvée pour {0}. Utilisez la commande &apos;setApiKey&apos; pour enregistrer une clé API pour une source..
        /// </summary>
        public static string NoApiKeyFound_fra {
            get {
                return ResourceManager.GetString("NoApiKeyFound_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato fornito alcun API Key  e non è stato possibile trovare API Key per {0}. Per salvare un API Key per una fonte usare il comando &apos;setApiKey&apos;..
        /// </summary>
        public static string NoApiKeyFound_ita {
            get {
                return ResourceManager.GetString("NoApiKeyFound_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API キーが指定されておらず、{0} の API キーが見つかりませんでした。ソースの API キーを保存するには、&apos;setApiKey&apos; コマンドを使用してください。.
        /// </summary>
        public static string NoApiKeyFound_jpn {
            get {
                return ResourceManager.GetString("NoApiKeyFound_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API 키가 제공되지 않았으므로 {0}에서 API 키를 찾을 수 없습니다. 소스에 대한 API 키를 저장하려면 &apos;setApiKey&apos; 명령을 사용하십시오..
        /// </summary>
        public static string NoApiKeyFound_kor {
            get {
                return ResourceManager.GetString("NoApiKeyFound_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano klucza interfejsu API i nie można znaleźć klucza interfejsu API dla {0}. Aby zapisać klucz interfejsu API dla źródła, użyj polecenia „setApiKey”..
        /// </summary>
        public static string NoApiKeyFound_plk {
            get {
                return ResourceManager.GetString("NoApiKeyFound_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhuma chave de API foi fornecida e nenhuma chave de API foi encontrada para {0}. Para salvar uma chave de API para uma origem, use o comando &quot;setApiKey..
        /// </summary>
        public static string NoApiKeyFound_ptb {
            get {
                return ResourceManager.GetString("NoApiKeyFound_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ API не указан, также не удалось найти ключ API для {0}. Чтобы сохранить ключ API для источника, используйте команду &quot;setApiKey&quot;..
        /// </summary>
        public static string NoApiKeyFound_rus {
            get {
                return ResourceManager.GetString("NoApiKeyFound_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Anahtarı belirtilmemiş ve {0} için hiçbir API Anahtarı bulunamadı. Bir kaynak için API Anahtarını kaydetmek için &apos;setApiKey&apos; komutunu kullanın..
        /// </summary>
        public static string NoApiKeyFound_trk {
            get {
                return ResourceManager.GetString("NoApiKeyFound_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update. The project does not contain a packages.config file..
        /// </summary>
        public static string NoPackagesConfig {
            get {
                return ResourceManager.GetString("NoPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found with packages.config..
        /// </summary>
        public static string NoProjectsFound {
            get {
                return ResourceManager.GetString("NoProjectsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet official package source.
        /// </summary>
        public static string OfficialPackageSourceName {
            get {
                return ResourceManager.GetString("OfficialPackageSourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [option] on &apos;{0}&apos; is invalid without a setter..
        /// </summary>
        public static string OptionInvalidWithoutSetter {
            get {
                return ResourceManager.GetString("OptionInvalidWithoutSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Version: {1}.
        /// </summary>
        public static string OutputNuGetVersion {
            get {
                return ResourceManager.GetString("OutputNuGetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added file &apos;{0}&apos;..
        /// </summary>
        public static string PackageCommandAddedFile {
            get {
                return ResourceManager.GetString("PackageCommandAddedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to build package from &apos;{0}&apos;..
        /// </summary>
        public static string PackageCommandAttemptingToBuildPackage {
            get {
                return ResourceManager.GetString("PackageCommandAttemptingToBuildPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to build symbols package for &apos;{0}&apos;..
        /// </summary>
        public static string PackageCommandAttemptingToBuildSymbolsPackage {
            get {
                return ResourceManager.GetString("PackageCommandAttemptingToBuildSymbolsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File from dependency is changed. Adding file &apos;{0}&apos;..
        /// </summary>
        public static string PackageCommandFileFromDependencyIsChanged {
            get {
                return ResourceManager.GetString("PackageCommandFileFromDependencyIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File from dependency is not changed. File &apos;{0}&apos; is not added..
        /// </summary>
        public static string PackageCommandFileFromDependencyIsNotChanged {
            get {
                return ResourceManager.GetString("PackageCommandFileFromDependencyIsNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of MinClientVersion argument is not a valid version..
        /// </summary>
        public static string PackageCommandInvalidMinClientVersion {
            get {
                return ResourceManager.GetString("PackageCommandInvalidMinClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: {0}.
        /// </summary>
        public static string PackageCommandIssueDescription {
            get {
                return ResourceManager.GetString("PackageCommandIssueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution: {0}.
        /// </summary>
        public static string PackageCommandIssueSolution {
            get {
                return ResourceManager.GetString("PackageCommandIssueSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue: {0}.
        /// </summary>
        public static string PackageCommandIssueTitle {
            get {
                return ResourceManager.GetString("PackageCommandIssueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build package. Ensure &apos;{0}&apos; includes assembly files. For help on building symbols package, visit {1}..
        /// </summary>
        public static string PackageCommandNoFilesForLibPackage {
            get {
                return ResourceManager.GetString("PackageCommandNoFilesForLibPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build package. Ensure &apos;{0}&apos; includes source and symbol files. For help on building symbols package, visit {1}..
        /// </summary>
        public static string PackageCommandNoFilesForSymbolsPackage {
            get {
                return ResourceManager.GetString("PackageCommandNoFilesForSymbolsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} issue(s) found with package &apos;{1}&apos;..
        /// </summary>
        public static string PackageCommandPackageIssueSummary {
            get {
                return ResourceManager.GetString("PackageCommandPackageIssueSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a nuspec or project file to use..
        /// </summary>
        public static string PackageCommandSpecifyInputFileError {
            get {
                return ResourceManager.GetString("PackageCommandSpecifyInputFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created package &apos;{0}&apos;..
        /// </summary>
        public static string PackageCommandSuccess {
            get {
                return ResourceManager.GetString("PackageCommandSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate &apos;{0} {1}&apos;. Make sure all packages exist in the packages folder before running update..
        /// </summary>
        public static string PackageDoesNotExist {
            get {
                return ResourceManager.GetString("PackageDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Allow NuGet to download missing packages.
        /// </summary>
        public static string PackageRestoreConsentCheckBoxText {
            get {
                return ResourceManager.GetString("PackageRestoreConsentCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing files from &apos;{0}&apos;..
        /// </summary>
        public static string PackagingFilesFromOutputPath {
            get {
                return ResourceManager.GetString("PackagingFilesFromOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do. This project does not specify any packages for NuGet to restore..
        /// </summary>
        public static string ProjectRestoreCommandNoPackagesConfigOrProjectJson {
            get {
                return ResourceManager.GetString("ProjectRestoreCommandNoPackagesConfigOrProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no default source, please specify a source..
        /// </summary>
        public static string PushCommandNoSourceError {
            get {
                return ResourceManager.GetString("PushCommandNoSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已推送你的程序包。.
        /// </summary>
        public static string PushCommandPackagePushed_chs {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已推入您的封裝。.
        /// </summary>
        public static string PushCommandPackagePushed_cht {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balíček byl předán..
        /// </summary>
        public static string PushCommandPackagePushed_csy {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Paket wurde mittels Push übertragen..
        /// </summary>
        public static string PushCommandPackagePushed_deu {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha insertado su proyecto..
        /// </summary>
        public static string PushCommandPackagePushed_esp {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre package a été transmis..
        /// </summary>
        public static string PushCommandPackagePushed_fra {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il pacchetto è stato compresso..
        /// </summary>
        public static string PushCommandPackagePushed_ita {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パッケージがプッシュされました。.
        /// </summary>
        public static string PushCommandPackagePushed_jpn {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 패키지가 푸시되었습니다..
        /// </summary>
        public static string PushCommandPackagePushed_kor {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakiet został wypchnięty..
        /// </summary>
        public static string PushCommandPackagePushed_plk {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pacote foi empurrado..
        /// </summary>
        public static string PushCommandPackagePushed_ptb {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пакет был отправлен..
        /// </summary>
        public static string PushCommandPackagePushed_rus {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paketiniz iletildi..
        /// </summary>
        public static string PushCommandPackagePushed_trk {
            get {
                return ResourceManager.GetString("PushCommandPackagePushed_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在将 {0} 推送到 {1}....
        /// </summary>
        public static string PushCommandPushingPackage_chs {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在將 {0} 推入 {1}....
        /// </summary>
        public static string PushCommandPushingPackage_cht {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probíhá předávání {0} do {1}....
        /// </summary>
        public static string PushCommandPushingPackage_csy {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} wird mittels Push an {1} übertragen....
        /// </summary>
        public static string PushCommandPushingPackage_deu {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertando {0} a {1}….
        /// </summary>
        public static string PushCommandPushingPackage_esp {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission de {0} à {1}….
        /// </summary>
        public static string PushCommandPushingPackage_fra {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprimendo {0} di {1}....
        /// </summary>
        public static string PushCommandPushingPackage_ita {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} を {1} にプッシュしています....
        /// </summary>
        public static string PushCommandPushingPackage_jpn {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}을(를) {1}에 푸시하는 중....
        /// </summary>
        public static string PushCommandPushingPackage_kor {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trwa wypychanie {0} do {1}....
        /// </summary>
        public static string PushCommandPushingPackage_plk {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empurrando {0} para {1} ....
        /// </summary>
        public static string PushCommandPushingPackage_ptb {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка {0} в {1}....
        /// </summary>
        public static string PushCommandPushingPackage_rus {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} öğesi {1} öğesine iletiliyor....
        /// </summary>
        public static string PushCommandPushingPackage_trk {
            get {
                return ResourceManager.GetString("PushCommandPushingPackage_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing took too long. You can change the default timeout of 300 seconds by using the -Timeout &lt;seconds&gt; option with the push command..
        /// </summary>
        public static string PushCommandTimeoutError {
            get {
                return ResourceManager.GetString("PushCommandTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; on resource type &apos;{1}&apos; is not a type of ResourceManager..
        /// </summary>
        public static string ResourcePropertyIncorrectType {
            get {
                return ResourceManager.GetString("ResourcePropertyIncorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource type &apos;{0}&apos; does not have an accessible static property named &apos;{1}&apos;..
        /// </summary>
        public static string ResourceTypeDoesNotHaveProperty {
            get {
                return ResourceManager.GetString("ResourceTypeDoesNotHaveProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;globalPackagesFolder&apos; setting is a relative path. To determine full path, please specify either -SolutionDirectory or a solution file as a parameter. To ignore &apos;globalPackagesFolder&apos; setting, specify -PackagesDirectory..
        /// </summary>
        public static string RestoreCommandCannotDetermineGlobalPackagesFolder {
            get {
                return ResourceManager.GetString("RestoreCommandCannotDetermineGlobalPackagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine the packages folder to restore NuGet packages. Please specify either -PackagesDirectory or -SolutionDirectory..
        /// </summary>
        public static string RestoreCommandCannotDeterminePackagesFolder {
            get {
                return ResourceManager.GetString("RestoreCommandCannotDeterminePackagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file does not exist: {0}..
        /// </summary>
        public static string RestoreCommandFileNotFound {
            get {
                return ResourceManager.GetString("RestoreCommandFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option -SolutionDirectory is not valid when restoring packages for a solution..
        /// </summary>
        public static string RestoreCommandOptionSolutionDirectoryIsInvalid {
            get {
                return ResourceManager.GetString("RestoreCommandOptionSolutionDirectoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring NuGet packages...
        ///To prevent NuGet from downloading packages during build, open the Visual Studio Options dialog, click on the NuGet Package Manager node and uncheck &apos;{0}&apos;..
        /// </summary>
        public static string RestoreCommandPackageRestoreOptOutMessage {
            get {
                return ResourceManager.GetString("RestoreCommandPackageRestoreOptOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file {0} cannot be found..
        /// </summary>
        public static string RestoreCommandProjectNotFound {
            get {
                return ResourceManager.GetString("RestoreCommandProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring NuGet packages for solution {0}..
        /// </summary>
        public static string RestoreCommandRestoringPackagesForSolution {
            get {
                return ResourceManager.GetString("RestoreCommandRestoringPackagesForSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring NuGet packages listed in packages.config file..
        /// </summary>
        public static string RestoreCommandRestoringPackagesFromPackagesConfigFile {
            get {
                return ResourceManager.GetString("RestoreCommandRestoringPackagesFromPackagesConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring NuGet packages listed in file {0}..
        /// </summary>
        public static string RestoreCommandRestoringPackagesListedInFile {
            get {
                return ResourceManager.GetString("RestoreCommandRestoringPackagesListedInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning for projects....
        /// </summary>
        public static string ScanningForProjects {
            get {
                return ResourceManager.GetString("ScanningForProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key &apos;{0}&apos; was saved for {1}..
        /// </summary>
        public static string SetApiKeyCommandApiKeySaved {
            get {
                return ResourceManager.GetString("SetApiKeyCommandApiKeySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The API Key &apos;{0}&apos; was saved for {1} and {2}..
        /// </summary>
        public static string SetApiKeyCommandDefaultApiKeysSaved {
            get {
                return ResourceManager.GetString("SetApiKeyCommandDefaultApiKeysSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to do. None of the projects in this solution specify any packages for NuGet to restore..
        /// </summary>
        public static string SolutionRestoreCommandNoPackagesConfigOrProjectJson {
            get {
                return ResourceManager.GetString("SolutionRestoreCommandNoPackagesConfigOrProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created &apos;{0}&apos; successfully..
        /// </summary>
        public static string SpecCommandCreatedNuSpec {
            get {
                return ResourceManager.GetString("SpecCommandCreatedNuSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists, use -Force to overwrite it..
        /// </summary>
        public static string SpecCommandFileExists {
            get {
                return ResourceManager.GetString("SpecCommandFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change from type &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        public static string UnableToConvertTypeError {
            get {
                return ResourceManager.GetString("UnableToConvertTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to extract metadata from &apos;{0}&apos;..
        /// </summary>
        public static string UnableToExtractAssemblyMetadata {
            get {
                return ResourceManager.GetString("UnableToExtractAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos;. Make sure the project has been built..
        /// </summary>
        public static string UnableToFindBuildOutput {
            get {
                return ResourceManager.GetString("UnableToFindBuildOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件不存在({0})。.
        /// </summary>
        public static string UnableToFindFile_chs {
            get {
                return ResourceManager.GetString("UnableToFindFile_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 檔案不存在 ({0})。.
        /// </summary>
        public static string UnableToFindFile_cht {
            get {
                return ResourceManager.GetString("UnableToFindFile_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soubor neexistuje ({0})..
        /// </summary>
        public static string UnableToFindFile_csy {
            get {
                return ResourceManager.GetString("UnableToFindFile_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei ist nicht vorhanden (&quot;{0}&quot;)..
        /// </summary>
        public static string UnableToFindFile_deu {
            get {
                return ResourceManager.GetString("UnableToFindFile_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe el archivo ({0})..
        /// </summary>
        public static string UnableToFindFile_esp {
            get {
                return ResourceManager.GetString("UnableToFindFile_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier n&apos;existe pas ({0})..
        /// </summary>
        public static string UnableToFindFile_fra {
            get {
                return ResourceManager.GetString("UnableToFindFile_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file non esiste ({0})..
        /// </summary>
        public static string UnableToFindFile_ita {
            get {
                return ResourceManager.GetString("UnableToFindFile_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルは存在しません ({0})。.
        /// </summary>
        public static string UnableToFindFile_jpn {
            get {
                return ResourceManager.GetString("UnableToFindFile_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일이 없습니다({0})..
        /// </summary>
        public static string UnableToFindFile_kor {
            get {
                return ResourceManager.GetString("UnableToFindFile_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik nie istnieje ({0})..
        /// </summary>
        public static string UnableToFindFile_plk {
            get {
                return ResourceManager.GetString("UnableToFindFile_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo não existe ({0})..
        /// </summary>
        public static string UnableToFindFile_ptb {
            get {
                return ResourceManager.GetString("UnableToFindFile_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл не существует ({0})..
        /// </summary>
        public static string UnableToFindFile_rus {
            get {
                return ResourceManager.GetString("UnableToFindFile_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya mevcut değil ({0})..
        /// </summary>
        public static string UnableToFindFile_trk {
            get {
                return ResourceManager.GetString("UnableToFindFile_trk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos;. Make sure they are specified in packages.config..
        /// </summary>
        public static string UnableToFindPackages {
            get {
                return ResourceManager.GetString("UnableToFindPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find project &apos;{0}&apos;..
        /// </summary>
        public static string UnableToFindProject {
            get {
                return ResourceManager.GetString("UnableToFindProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find solution &apos;{0}&apos;..
        /// </summary>
        public static string UnableToFindSolution {
            get {
                return ResourceManager.GetString("UnableToFindSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the packages folder. Verify all the packages are restored before running &apos;nuget.exe update&apos;..
        /// </summary>
        public static string UnableToLocatePackagesFolder {
            get {
                return ResourceManager.GetString("UnableToLocatePackagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate project file for &apos;{0}&apos;..
        /// </summary>
        public static string UnableToLocateProjectFile {
            get {
                return ResourceManager.GetString("UnableToLocateProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command: &apos;{0}&apos;.
        /// </summary>
        public static string UnknowCommandError {
            get {
                return ResourceManager.GetString("UnknowCommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown option: &apos;{0}&apos;.
        /// </summary>
        public static string UnknownOptionError {
            get {
                return ResourceManager.GetString("UnknownOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid target framework..
        /// </summary>
        public static string UnsupportedFramework {
            get {
                return ResourceManager.GetString("UnsupportedFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates from {0}..
        /// </summary>
        public static string UpdateCommandCheckingForUpdates {
            get {
                return ResourceManager.GetString("UpdateCommandCheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running NuGet.exe {0}..
        /// </summary>
        public static string UpdateCommandCurrentlyRunningNuGetExe {
            get {
                return ResourceManager.GetString("UpdateCommandCurrentlyRunningNuGetExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet.exe is up to date..
        /// </summary>
        public static string UpdateCommandNuGetUpToDate {
            get {
                return ResourceManager.GetString("UpdateCommandNuGetUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos; package..
        /// </summary>
        public static string UpdateCommandUnableToFindPackage {
            get {
                return ResourceManager.GetString("UpdateCommandUnableToFindPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NuGet.CommandLine package. Unable to locate NuGet.exe within the package..
        /// </summary>
        public static string UpdateCommandUnableToLocateNuGetExe {
            get {
                return ResourceManager.GetString("UpdateCommandUnableToLocateNuGetExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful..
        /// </summary>
        public static string UpdateCommandUpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateCommandUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating NuGet.exe to {0}..
        /// </summary>
        public static string UpdateCommandUpdatingNuGet {
            get {
                return ResourceManager.GetString("UpdateCommandUpdatingNuGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating &apos;{0}&apos;....
        /// </summary>
        public static string UpdatingProject {
            get {
                return ResourceManager.GetString("UpdatingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using &apos;{0}&apos; for metadata..
        /// </summary>
        public static string UsingNuspecForMetadata {
            get {
                return ResourceManager.GetString("UsingNuspecForMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found packages.config. Using packages listed as dependencies.
        /// </summary>
        public static string UsingPackagesConfigForDependencies {
            get {
                return ResourceManager.GetString("UsingPackagesConfigForDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the &apos;{0}&apos; operation with an &apos;HTTP&apos; source, &apos;{1}&apos;. Non-HTTPS access will be removed in a future version. Consider migrating to an &apos;HTTPS&apos; source..
        /// </summary>
        public static string Warning_HttpServerUsage {
            get {
                return ResourceManager.GetString("Warning_HttpServerUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the &apos;{0}&apos; operation with &apos;HTTP&apos; sources: {1}
        ///Non-HTTPS access will be removed in a future version. Consider migrating to &apos;HTTPS&apos; sources..
        /// </summary>
        public static string Warning_HttpSources_Multiple {
            get {
                return ResourceManager.GetString("Warning_HttpSources_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到符号程序包“{0}”，但未为符号服务器指定 API 密钥。若要保存 API 密钥，请运行“NuGet.exe setApiKey [来自 http://www.NuGet.org 的 API 密钥]”。.
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_chs {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_chs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找到符號封裝 &apos;{0}&apos;，但並未為符號伺服器指定 API 索引鍵。若要儲存 API 索引鍵，請執行 &apos;NuGet.exe setApiKey [http://www.NuGet.org 中的 API 索引鍵]&apos;。.
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_cht {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_cht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byl nalezen balíček symbolů {0}, ale pro server symbolů nebyl zadán žádný klíč API. Chcete-li uložit klíč API, spusťte příkaz NuGet.exe setApiKey [klíč API z webu http://www.NuGet.org]..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_csy {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_csy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Symbolpaket &quot;{0}&quot; wurde gefunden, es wurde jedoch kein API-Schlüssel für den Symbolserver angegeben. Führen Sie zum Speichern eines API-Schlüssels &quot;NuGet.exe setApiKey [Ihr API-Schlüssel von http://www.NuGet.org]&quot; aus..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_deu {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_deu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha encontrado el paquete de símbolos &apos;{0}&apos;, pero no se ha especificado ninguna clave API para el servidor de símbolos. Para guardar una clave API, ejecute &apos;NuGet.exe setApiKey [su clave API de http://www.NuGet.org]&apos;..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_esp {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_esp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package de symboles &apos;{0}&apos; trouvé, mais aucune clé API n&apos;a été spécifiée pour le serveur de symboles. Pour enregistrer une clé API, exécutez &apos;NuGet.exe setApiKey [votre clé API provenant de http://www.NuGet.org]&apos;..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_fra {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_fra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trovato pacchetto simboli &apos;{0}&apos;, ma non è stata specificata alcuna API key per il symbol server. Per salvare una API Key, eseguire &apos;NuGet.exe setApiKey [ API key da http://www.NuGet.org]&apos;..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_ita {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シンボル パッケージ &apos;{0}&apos; が見つかりましたが、シンボル サーバーの API キーが指定されていません。API キーを保存するには、&apos;NuGet.exe setApiKey [your API key from http://www.NuGet.org]&apos; を実行してください。.
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_jpn {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 기호 패키지 &apos;{0}&apos;을(를) 찾았지만 기호 서버에 대한 API 키가 지정되지 않았습니다. API 키를 저장하려면 &apos;NuGet.exe setApiKey [http://www.NuGet.org의 API 키]&apos;를 실행하십시오..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_kor {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odnaleziono pakiet symboli „{0}”, ale dla serwera symboli nie został określony klucz interfejsu API. Aby zapisać klucz interfejsu API, uruchom polecenie „NuGet.exe setApiKey [Twój klucz interfejsu API ze strony http://www.NuGet.org]”..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_plk {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_plk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O pacote símbolos &apos;{0}&apos; foi localizado, mas nenhuma chave de API foi especificada para o servidor de símbolos. Para salvar uma chave de API,  execute &quot;NuGet.exe setApiKey [sua chave de API de http://www.NuGet.org]&quot;..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_ptb {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_ptb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружен пакет символов &quot;{0}&quot;, но для сервера символов не был указан ключ API. Чтобы сохранить ключ API, выполните команду &quot;NuGet.exe setApiKey [ваш ключ API с сайта http://www.NuGet.org]&quot;..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_rus {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos; simge paketi bulundu ancak simge sunucusu için hiçbir API anahtarı belirtilmemiş. Bir API Anahtarını kaydetmek için &apos;NuGet.exe setApiKey [http://www.NuGet.org sayfasından aldığınız API anahtarı]&apos; öğesini çalıştırın..
        /// </summary>
        public static string Warning_SymbolServerNotConfigured_trk {
            get {
                return ResourceManager.GetString("Warning_SymbolServerNotConfigured_trk", resourceCulture);
            }
        }
    }
}
